# Generated by Django 5.1.4 on 2024-12-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('org_city', models.CharField(max_length=50)),
                ('org_district', models.CharField(max_length=50)),
                ('org_pincode', models.PositiveIntegerField()),
                ('reg_no', models.CharField(max_length=50)),
                ('org_mail', models.EmailField(max_length=254)),
                ('org_phno', models.CharField(max_length=20)),
                ('org_poc', models.CharField(max_length=50)),
                ('org_poc_no', models.CharField(max_length=20)),
                ('j_date', models.CharField(max_length=20)),
            ],
        ),
    ]
