# Generated by Django 5.1.4 on 2024-12-30 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(default='organization', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
