# Generated by Django 5.1.4 on 2025-01-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_admin_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_poc_no',
        ),
    ]
