# Generated by Django 5.1.4 on 2025-01-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_donpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donpayment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failedn ')], default='Pending', max_length=50),
        ),
    ]
