# Generated by Django 5.1.4 on 2025-01-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_donpayment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('email', models.CharField(max_length=20)),
                ('materials', models.CharField(choices=[('clothes', 'Clothes'), ('school_materials', 'School Materials')], max_length=20)),
                ('time_limit', models.DateField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
