# Generated by Django 5.1.4 on 2025-01-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_name_payment_namecus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='namecus',
            new_name='name',
        ),
    ]
